stages:
  - test
  - build
  - deploy

.job_template: &base-image
  image: node:8.11

.job_template: &test-image
  <<: *base-image

.job_template: &build-image
  <<: *base-image

.job_template: &deploy-image
  <<: *base-image

.job_template: &only-staging-production-tag
  only:
    - /^(staging-|v)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &only-staging-tag
  only:
    - /^(staging-)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &only-production-tag
  only:
    - /^(v)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &tags-docker
  tags:
    - docker

.job_template: &test
  <<: *test-image
  <<: *only-staging-production-tag
  <<: *tags-docker
  stage: test
  before_script:
    - yarn install
  script:
    - yarn run test
  when: on_success

.job_template: &build
  <<: *build-image
  <<: *only-staging-production-tag
  <<: *tags-docker
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build
  artifacts:
    paths:
      - .serverless
      - node_modules
      - package-lock.json
      - package.json
      - serverless.yml
      - yarn.lock

.job_template: &deploy
  <<: *deploy-image
  <<: *only-staging-production-tag
  <<: *tags-docker
  stage: deploy
  script:
    - yarn run deploy
  when: on_success

test:
  <<: *test
  <<: *only-staging-production-tag
  variables:
    NODE_ENV: "test"

build:
  <<: *build
  <<: *only-staging-production-tag
  dependencies:
    - test

deploy-production:
  <<: *deploy
  <<: *only-production-tag
  dependencies:
    - build
  environment:
    name: production
