stages:
  - build
  - test
  - deploy

.job_template: &base-image
  image: node:8.11

.job_template: &build-image
  <<: *base-image

.job_template: &test-image
  <<: *base-image

.job_template: &deploy-image
  <<: *base-image

.job_template: &only-staging-production-tag
  only:
    - /^(staging-|v)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &only-staging-tag
  only:
    - /^(staging-)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &only-production-tag
  only:
    - /^(v)(\d+\.\d+\.\d+)\-?(\w*)$/

.job_template: &tags-docker
  tags:
    - docker

.job_template: &build
  <<: *build-image
  <<: *only-staging-production-tag
  <<: *tags-docker
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - config
      - helpers
      - node_modules
      - package-lock.json
      - package.json
      - serverless.yml
      - src
      - yarn.lock

.job_template: &deploy
  <<: *deploy-image
  <<: *only-staging-production-tag
  <<: *tags-docker
  stage: deploy
  script:
    - yarn run deploy
  when: on_success

build-production:
  <<: *build
  <<: *only-production-tag

deploy-production:
  <<: *deploy
  <<: *only-production-tag
  dependencies:
    - build-production
  environment:
    name: production
  variables:
    CARD_GENERATOR_URL: "http://cdn-static.rpc.com.br/interatividade/hotsites/dia-dos-pais/homenagem-3.html"
    CARD_STORAGE_PATH: "interatividade/cartao-dia-dos-pais"
    COR_SER_CLOCON_URL: "https://corporativo-cloudconvert.grpcom.com.br"
    IAM_ROLE: "arn:aws:iam::852929616770:role/lambda-comitex-vocenarpc-interactivity-cartaodiadospais"
    STORAGE_BUCKET: "app-rpc-static"
