version: "2"

networks:
  default:
    external:
      name: main

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serverless.templates.tecnologia
    image: docker.grpcom.local/tecnologia/templates/serverless:development
    restart: on-failure:4
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=api,application
      - NODE_ENV=development
      - VIRTUAL_HOST=serverless.templates.tecnologia
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    external_links:
      - nginx-proxy.web-base
    volumes:
      - .:/application
      - .:/mnt/base
      - /application/node_modules
    working_dir: /application
    command:
      - yarn
      - run
      - start:watch
