version: '3'

networks:
  default:
    external:
      name: main

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws.nodejs.serverless.boilerplate.slergberg.localhost
    image: slergberg/boilerplate-serverless-nodejs-aws
    restart: on-failure:4
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=api,application
      - NODE_ENV=development
      - VIRTUAL_HOST=aws.nodejs.serverless.boilerplate.slergberg.localhost
      - VIRTUAL_PORT=3000
    expose:
      - '3000'
    external_links:
      - nginx-proxy.web-dev-svc.localhost
    volumes:
      - .:/application
      - /application/node_modules
    working_dir: /application
    command:
      - npm
      - run
      - start
