service: slergberg-boilerplate-serverless-nodejs-aws

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  deploymentBucket: slergberg-deployment-bucket
  region: us-east-1
  role: ${env:IAM_ROLE, ''}
  runtime: nodejs8.10
  stage: ${env:STAGE, 'production'}

  environment:

custom:
  package:
    prefix: sle-boi-ser-nod-aws

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true
  exclude:
    - ./**
  include:
    - config/**
    - helpers/**
    - node_modules/**
    - package.json
    - src/**

functions:
  root:
    name: ${self:custom.package.prefix}-root
    handler: src/main/root.handler
    events:
      - http:
          path: /
          method: get
          cors: true

  healthCheck:
    name: ${self:custom.package.prefix}-health-check
    handler: src/main/healthCheck.handler
    events:
      - http:
          path: /health_check
          method: get
          cors: true
